server:
   applicationConnectors:
       - type: http
         port: 1738

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: c:/users/moe/desktop/quotevault/quotevault.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: c:/users/moe/desktop/quotevault/arch/quotevault-%d.log
      archivedFileCount: 5
      timeZone: UTC
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout

database:
  driverClass: org.h2.Driver
  user: admin_bourjm
  password: admin
  url: jdbc:h2:tcp://localhost/~/quotevault